# Generated by Django 2.2.7 on 2019-11-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hashtag',
            fields=[
                ('tagName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tagCnt', models.IntegerField(default=0)),
                ('likeCnt', models.IntegerField(default=0)),
            ],
        ),
    ]
