# Generated by Django 2.2.7 on 2019-11-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='tagDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
