# Generated by Django 2.2.7 on 2019-11-28 13:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='hashtag',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
