# Generated by Django 2.2.4 on 2019-12-01 13:21

import django.contrib.auth.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='hashtag',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='like',
            field=models.IntegerField(blank=True, default=0, verbose_name=django.contrib.auth.models.User),
        ),
    ]
