# Generated by Django 2.2.4 on 2019-11-30 14:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='text',
        ),
        migrations.AddField(
            model_name='photo',
            name='hashtag',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
