# Generated by Django 2.2.4 on 2019-12-02 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0002_auto_20191201_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='text',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='like',
        ),
        migrations.AddField(
            model_name='photo',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
