# Generated by Django 2.0.13 on 2019-12-01 11:57

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20191130_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='like',
        ),
        migrations.AddField(
            model_name='photo',
            name='like',
            field=models.IntegerField(blank=True, default=0, verbose_name=django.contrib.auth.models.User),
        ),
    ]
